[package]
name = "caponata_common"
version = "0.1.0"

license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
uuid = { version = "1.18.*", features = ["v4"] }
